import type { Metadata, NextPage } from 'next'
import './globals.css'
import Navbar from '@/components/navbar'
import { jost } from './fonts'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface IRootLayoutProps {
	children: React.ReactNode
}

const RootLayout: NextPage<IRootLayoutProps> = ({ children }) => {
	return (
		<html lang='en'>
			<body className={jost.className}>
				<Navbar />
				{children}
			</body>
		</html>
	)
}

export default RootLayout
